### ISSUE TITLE
Crash immediately after pressing the "Take Picture" button.

### ISSUE THREAD

**Issue by wilsonhws** [SandroMachado/openalpr-android#53] opened 2017-08-01 18:29 UTC
Hi, can you make a detailed tutorial about this openalpr library? I've been trying to import this lib to my project, but there's errors everywhere. Please help.

**Comment by arnoldcoder** [comment] 2017-08-02 05:40
I've just created a new project, added the dependencies and copied the sample project's Mainactivity. You also have to add WRITE_EXTERNAL_STORAGE permission to the AndroidManifest.xml file.

**Comment by arnoldcoder** [comment] 2017-08-02 05:48
If you are using Android Studio, you should have an error related to this permission miss.

Here is my sample working project
https://www.dropbox.com/s/920i716rgv2yud4/licence.zip?dl=0

**Comment by wilsonhws** [comment] 2017-08-02 16:16
![image](https://user-images.githubusercontent.com/26358305/28883310-8fe0484c-77e0-11e7-9dce-7e66b0caf738.png)

@arnoldcoder Thanks for the dropbox link, but this is the error that I've been getting on my S7 edge. Is this the permission error you talked about?

**Comment by wilsonhws** [comment] 2017-08-02 17:13
@arnoldcoder Thanks, I've solved it by setting the target sdk version to 22.

**Comment by SandroMachado** [comment] 2017-08-03 00:00
Looks like the issue is fixed. I will close the issue, please let me know if I need to reopen.

**Closed as completed by SandroMachado** 2017-08-03 00:00 UTC
